import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CartPanel from "@/app/ui/cart-panel";
import {createCart} from "@/app/lib/data";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cart = await createCart()
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className={'store-header'}>
          <Link href="/" className={'flex gap-4 items-center w-fit'}>
            <em className={'fa fa-store text-orange-500 text-[40px]'}></em>
            <span className={'font-bold text-lg'}>Mi<span className={'text-orange-500'}>Tienda</span>Online</span>
          </Link>
          <CartPanel cart={cart}></CartPanel>
        </header>
        <main className={'store-main-content'}>
          {children}
        </main>
      </body>

    </html>
  );
}
